# Generated by Django 4.2.7 on 2024-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
