# Generated by Django 4.2.7 on 2024-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyer_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerclient',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
