# Generated by Django 4.2.7 on 2024-05-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_photo_news_الصورة_rename_title_news_العنوان_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='المؤلف',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='المحتوى',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='تاريخ_الإنشاء',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='الصورة',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='العنوان',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='تاريخ_التحديث',
            new_name='updated_at',
        ),
    ]
