# Generated by Django 4.2.7 on 2024-05-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_المؤلف_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerclient',
            name='finalized',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
