# Generated by Django 4.2.7 on 2024-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('3_minutes', '3 Minutes'), ('1_year', '1 Year'), ('6_months', '6 Months')], max_length=50, null=True),
        ),
    ]
