# Generated by Django 4.2.7 on 2024-05-16 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rdv_nrdv_notaryclients_lawyerclients_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='npaiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpartie', models.CharField(max_length=60)),
                ('spartie', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('prix', models.FloatField()),
                ('remarques', models.CharField(max_length=120)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notary')),
            ],
        ),
    ]
