# Generated by Django 4.2.7 on 2024-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_npaiements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aff',
            old_name='Nclient',
            new_name='Nomclient',
        ),
        migrations.RemoveField(
            model_name='aff',
            name='supprime',
        ),
        migrations.RemoveField(
            model_name='aff',
            name='user1',
        ),
        migrations.AddField(
            model_name='aff',
            name='details',
            field=models.TextField(default='gggg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aff',
            name='tel',
            field=models.IntegerField(default=222222222222222222222),
            preserve_default=False,
        ),
    ]
