# Generated by Django 4.2.7 on 2024-05-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_nclient_aff_nomclient_remove_aff_supprime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='archiveaff',
        ),
    ]
