# Generated by Django 4.2.7 on 2024-05-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_archiveaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documents',
        ),
    ]
